FROM debian:11

RUN echo 'deb  http://ftp.de.debian.org/debian/  oldoldstable main contrib non-free' >> /etc/apt/sources.list
RUN echo 'deb-src  http://ftp.de.debian.org/debian/  oldoldstable main contrib non-free' >> /etc/apt/sources.list
RUN echo 'deb  http://ftp.de.debian.org/debian/  oldstable main contrib non-free' >> /etc/apt/sources.list
RUN echo 'deb-src  http://ftp.de.debian.org/debian/  oldstable main contrib non-free' >> /etc/apt/sources.list
RUN echo 'deb  http://ftp.de.debian.org/debian/  stable main contrib non-free' >> /etc/apt/sources.list
RUN echo 'deb-src  http://ftp.de.debian.org/debian/  stable main contrib non-free' >> /etc/apt/sources.list

RUN apt update

RUN apt-get install -y \
    wget \
    libcairo2-dev 	\
    libjpeg62-turbo-dev \
    libpng-dev \
    libossp-uuid-dev \
    libpango1.0-dev \
    libssh2-1-dev \
    libssl-dev \
    uuid-dev \
    make \
    gcc-6  \
    g++-6



RUN apt-get install -y openjdk-11-jdk

RUN useradd -m -U -d /opt/tomcat -s /bin/false tomcat

#https://downloads.apache.org/tomcat/tomcat-9/v9.0.53/bin/apache-tomcat-9.0.53.tar.gz

#VERSION=9.0.35

RUN wget http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz -P ~

#RUN mkdir /opt/tomcat

RUN tar -xzf ~/apache-tomcat-9.0.35.tar.gz -C /opt/tomcat/
RUN ls /opt/tomcat/apache-tomcat-9.0.35/

RUN chown -R tomcat: /opt/tomcat
#RUN ls /opt/tomcat
RUN chmod +x /opt/tomcat/apache-tomcat-9.0.35/bin/*.sh

##############################
# Configuration du service
COPY tomcat /etc/init.d/tomcat

RUN cat /etc/init.d/tomcat

RUN chmod ug+x /etc/init.d/tomcat

#################################

#ufw allow 8080
#RUN systemctl daemon-reload
#RUN systemctl enable --now tomcat
#RUN mkdir /tmp
WORKDIR /tmp
RUN wget https://archive.apache.org/dist/guacamole/0.9.14/source/guacamole-server-0.9.14.tar.gz
RUN ls
RUN tar xzf guacamole-server-0.9.14.tar.gz
WORKDIR /tmp/guacamole-server-0.9.14

#RUN cd ~/guacamole-server-1.3.0
RUN ln -s /usr/bin/gcc-6 /usr/bin/gcc
RUN ./configure --with-init-dir=/etc/init.d
RUN make
RUN make install
RUN ldconfig
#RUN systemctl daemon-reload
#RUN systemctl start guacd
#RUN systemctl enable guacd

RUN mkdir /etc/guacamole
RUN wget https://archive.apache.org/dist/guacamole/0.9.14/binary/guacamole-0.9.14.war
RUN mv guacamole-0.9.14.war /etc/guacamole/guacamole.war

RUN ln -s /etc/guacamole/guacamole.war /opt/tomcat/apache-tomcat-9.0.35/webapps

RUN find / -name tomcatapp
#RUN ln -s /etc/guacamole/guacamole.war /opt/tomcat/tomcatapp/webapps
RUN ln -s /etc/guacamole /opt/tomcat/apache-tomcat-9.0.35/.guacamole

EXPOSE 8080

#RUN update-rc.d tomcat defaults
#RUN systemctl restart tomcat guacd

ENTRYPOINT ["/init"]












